<expr>          ::= <sub_expr> TkEps
<sub_expr>      ::= <seq> '|' <sub_expr> | <seq>
<seq>           ::= <sub_seq> | ''
<sub_seq>       ::= <star> <sub_seq> | <star>
<star>          ::= <factor> '*' | <factor>
<factor>        ::= '(' <sub_expr> ')' | TkChar